# Generated by Django 3.0.1 on 2020-02-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_op_food_picture_100g'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='categorie',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='op_food',
            old_name='nom',
            new_name='name',
        ),
    ]
