# Generated by Django 3.0.1 on 2020-04-02 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0006_auto_20200305_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitute',
            name='user',
        ),
        migrations.AddField(
            model_name='substitute',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
