# Generated by Django 3.0.1 on 2020-02-07 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='op_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=1)),
                ('ingredients', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('id_categorie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.categories')),
            ],
        ),
        migrations.CreateModel(
            name='substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.op_food')),
                ('user', models.ManyToManyField(blank=True, related_name='substitute', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
