# Generated by Django 3.0.1 on 2020-02-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='op_food',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='op_food',
            old_name='store',
            new_name='nutritional_values',
        ),
        migrations.AddField(
            model_name='op_food',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
